import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import React from "react";

const Profile = ({ data }) => {
  const router = useRouter();
  //   console.log(data);
  const profile = data[0];
  const {
    fullName,
    email,
    phone,
    address,
    age,
    gender,
    citizenship,
    nameAsShown,
    birthPlace,
    dob,
    maritalStatus,
    occupation,
    countryOfInterest,
    countryOfCitizenship,
    Education,
    mailingAddress,
    purposeOfTraveling,
  } = profile;

  const goBack = () => {
    router.back();
  };

  return (
    <>
      <Head>
        <title>Travel Manager | Clients</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full h-auto overflow-y-auto">
        <div className="lg:mx-14 lg:my-10 mx-3 my-2 flex flex-col gap-6">
          <div className="flex flex-col gap-1 lg:gap-1">
            <p className="text-xl lg:text-2xl font-semibold">Client Profile</p>
            <p className="text-base lg:text-lg text-[#b8bbbf]">
              View client profile here
            </p>
          </div>

          {/* profile details */}
          <div className="bg-white w-full flex flex-col gap-8 border rounded-md overflow-y-auto">
            {/* top */}
            <div className="bg-[#F1F1F1] flex flex-col gap-4 mt-7 mx-2 lg:mx-6 rounded-lg">
              <div className="flex flex-col gap-4 my-7 mx-6">
                <p className="text-xs lg:text-sm font-semibold">
                  Client&#39;s picture
                </p>
                <div className="flex items-center gap-4">
                  <div className="rounded-full md:w-[100px] h-[70px] w-[70px] md:h-[100px]">
                    <Image
                      src={"/blank-profile-picture.webp"}
                      alt="Client's picture"
                      width={70}
                      height={70}
                      className="m-auto md:w-[100px] h-[70px] w-[70px] md:h-[100px] object-cover rounded-full"
                    />
                  </div>
                  <div className="flex flex-col gap-2">
                    <p className="text-xs lg:text-sm font-semibold">
                      {fullName}
                    </p>
                    <p className="text-xs lg:text-sm text-[#a0a0a0]">{email}</p>
                    <div className="flex gap-3 text-xs lg:text-sm text-[#a0a0a0]">
                      <p>{gender}</p>
                      <p>{age}</p>
                      <p>{citizenship}</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* details */}
            <div className="lg:mx-6 mx-2 flex justify-between lg:w-[90%]">
              {/* left */}
              <div className="flex flex-col gap-6">
                {/* 1 */}
                <div className="flex flex-col text-xs lg:text-sm font-semibold">
                  <p className="text-[#a0a0a0]">Full Name</p>
                  <p>{fullName}</p>
                </div>
                {/* 2 */}
                <div className="flex flex-col text-xs lg:text-sm font-semibold">
                  <p className="text-[#a0a0a0]">
                    Applicant Fullname{" "}
                    <span className="text-[#da9e9e]">
                      (as shown in passport)
                    </span>
                  </p>
                  <p>{nameAsShown}</p>
                </div>
                {/* 3 */}
                <div className="flex justify-between">
                  <div className="flex flex-col text-xs lg:text-sm font-semibold">
                    <p className="text-[#a0a0a0]">Place of birth</p>
                    <p>{birthPlace}</p>
                  </div>
                  <div className="flex flex-col text-xs lg:text-sm font-semibold">
                    <p className="text-[#a0a0a0]">Date pf birth</p>
                    <p>{dob}</p>
                  </div>
                </div>
                {/* 4 */}
                <div className="flex flex-col text-xs lg:text-sm font-semibold">
                  <p className="text-[#a0a0a0]">Marital Status</p>
                  <p>{maritalStatus}</p>
                </div>
                {/* 5 */}
                <div className="flex flex-col text-xs lg:text-sm font-semibold">
                  <p className="text-[#a0a0a0]">Current Occupation</p>
                  <p>{occupation}</p>
                </div>
                {/* 6 */}
                <div className="flex flex-col text-xs lg:text-sm font-semibold">
                  <p className="text-[#a0a0a0]">Residential Address</p>
                  <p>{address}</p>
                </div>
                {/* 7 */}
                <div className="flex flex-col text-xs lg:text-sm font-semibold">
                  <p className="text-[#a0a0a0]">Country of Interest</p>
                  <p>{countryOfInterest}</p>
                </div>
              </div>

              {/* right */}
              <div className="flex flex-col gap-6">
                {/* 1 */}
                <div className="flex flex-col text-xs lg:text-sm font-semibold">
                  <p className="text-[#a0a0a0]">Email</p>
                  <p>{email}</p>
                </div>
                {/* 2 */}
                <div className="flex flex-col text-xs lg:text-sm font-semibold">
                  <p className="text-[#a0a0a0]">Gender</p>
                  <p>{gender}</p>
                </div>
                {/* 3 */}
                <div className="flex flex-col text-xs lg:text-sm font-semibold">
                  <p className="text-[#a0a0a0]">Country of citizenship</p>
                  <p>{countryOfCitizenship}</p>
                </div>
                {/* 4 */}
                <div className="flex flex-col text-xs lg:text-sm font-semibold">
                  <p className="text-[#a0a0a0]">
                    Education{" "}
                    <span className="text-[#da9e9e]">
                      (Clients highest level of education)
                    </span>
                  </p>
                  <p>{Education}</p>
                </div>
                {/* 5 */}
                <div className="flex flex-col text-xs lg:text-sm font-semibold">
                  <p className="text-[#a0a0a0]">Phone Number</p>
                  <p>{phone}</p>
                </div>
                {/* 6 */}
                <div className="flex flex-col text-xs lg:text-sm font-semibold">
                  <p className="text-[#a0a0a0]">Mailing Address</p>
                  <p>{mailingAddress}</p>
                </div>
                {/* 7 */}
                <div className="flex flex-col text-xs lg:text-sm font-semibold">
                  <p className="text-[#a0a0a0]">Purpose of traveling</p>
                  <p>{purposeOfTraveling}</p>
                </div>
              </div>
            </div>
            <button
              onClick={goBack}
              className="bg-[#ddaa3d] text-white self-end lg:mx-6 mx-2 my-6 lg:my-10 w-28 lg:w-32 py-1 lg:py-1.5 rounded-md"
            >
              Back
            </button>
          </div>
        </div>
      </div>
    </>
  );
};

export default Profile;

export async function getStaticProps(context) {
  const id = context?.params.profile;
  const { ClientData } = await import("/data/clientData.json");

  const data = ClientData.filter((client) => client.id == id);

  return {
    props: {
      data,
    },
  };
}

export async function getStaticPaths() {
  const { ClientData } = await import("/data/clientData.json");

  const paths = ClientData.map((val) => {
    return {
      params: {
        profile: val.id.toString(),
      },
    };
  });

  return {
    paths,
    fallback: false,
  };
}
