import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import { AiOutlineSearch } from "react-icons/ai";

const Clients = ({ data }) => {
  const router = useRouter();
  const clientData = data;

  return (
    <>
      <Head>
        <title>Travel Manager | Clients</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full h-fit overflow-y-auto">
        <div className="lg:mx-14 lg:my-10 mx-3 my-2 flex flex-col gap-6">
          <div className="flex flex-col gap-1 lg:gap-1">
            <p className="text-xl lg:text-2xl font-semibold">Clients</p>
            <p className="text-base lg:text-lg text-[#b8bbbf]">
              Here&#39;s the client list
            </p>
          </div>

          {/* table of client list */}
          <div className="bg-white w-full flex flex-col gap-8 rounded-md">
            {/* search input and button */}
            <div className="flex justify-between gap-2 mx-2 lg:mx-8 mt-8">
              <div className="relative flex w-[65%] lg:w-[85%]">
                <AiOutlineSearch
                  size={15}
                  className="absolute text-[#b8bbbf] top-2 lg:top-2.5 left-2"
                />
                <input
                  type="text"
                  placeholder="search by name, email ..."
                  className="border-2 w-full text-xs lg:text-sm rounded-md pl-6 lg:pl-8 py-1.5 outline-none"
                />
              </div>
              <button className="bg-[#ddaa3d] rounded-md text-white text-xs lg:text-sm px-2 py-1">
                Add new client
              </button>
            </div>
            {/* table */}
            <div className="overflow-x-auto flex lg:justify-start mb-4">
              <table className="w-full text-left mx-2 lg:mx-8">
                <thead className="text-xs lg:text-sm font-medium bg-[#fbf6eb] border-b-2 border-[#ddaa3d]">
                  <tr>
                    <th className="py-4">Name</th>
                    <th className="py-4">Email</th>
                    <th className="py-4">Phone</th>
                    <th className="py-4">Residential Address</th>
                  </tr>
                </thead>
                <tbody className="text-[#868d94] text-xs lg:text-sm">
                  {clientData?.length > 0 ? (
                    clientData?.map(
                      ({ id, fullName, email, phone, address }) => (
                        <tr
                          key={id}
                          onClick={() => router.push(`/clients/${id}`)}
                          className="hover:bg-[#fbf6eb] hover:border-l-4 border-[#ddaa3d] cursor-pointer"
                        >
                          <td className="py-5">{fullName}</td>
                          <td className="py-5">{email}</td>
                          <td className="py-5">{phone}</td>
                          <td className="py-5">{address}</td>
                        </tr>
                      )
                    )
                  ) : (
                    <tr className="border-y">
                      <td colSpan="6" className="py-4">
                        <p>No clients data available</p>
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Clients;

export async function getStaticProps() {
  const { ClientData } = await import("/data/clientData.json");

  return {
    props: {
      data: ClientData,
    },
  };
}
