import Head from "next/head";
import { Inter } from "next/font/google";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();

  const handleLogin = (e) => {
    e.preventDefault();
    router.push("/workspace");
  };

  return (
    <>
      <Head>
        <title>Travel Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-[#ddaa3d] w-full h-screen flex justify-center items-center relative">
        {/* login div */}
        <div className="bg-white w-[22rem] lg:w-[33rem] flex flex-col gap-7 shadow-2xl z-50">
          <div className="flex justify-between mx-8 mt-9 lg:mt-16">
            <div className="flex flex-col text-black gap-1">
              <p className="font-bold text-sm lg:text-base">Login</p>
              <p className="text-xs lg:text-sm">Login to your account</p>
            </div>
            <div className="font-bold text-xl lg:text-2xl">LOGO</div>
          </div>

          {/* login form */}
          <div className="mx-8 mb-9 lg:mb-16">
            <form className="flex flex-col gap-4">
              <div className="flex flex-col gap-2">
                <label className="text-xs lg:text-sm font-semibold">
                  Email
                </label>
                <input
                  type="email"
                  className="border border-slate-400 py-3 outline-none pl-2"
                />
              </div>
              <div className="flex flex-col gap-2">
                <label className="text-xs lg:text-sm font-semibold">
                  Password
                </label>
                <input
                  type="password"
                  className="border border-slate-400 py-3 outline-none pl-2"
                />
              </div>
              <button
                onClick={handleLogin}
                className="bg-[#ddaa3d] text-white w-[80%] self-center py-3 text-xs lg:text-sm mt-8"
              >
                Login
              </button>
            </form>
          </div>
        </div>

        {/* wave svg */}
        {/* <svg
          className="absolute bottom-0 left-0"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 1440 320"
          height="30rem"
        >
          <path
            fill=" #fff"
            fill-opacity="1"
            d="M0,288L40,250.7C80,213,160,139,240,106.7C320,75,400,85,480,96C560,107,640,117,720,144C800,171,880,213,960,229.3C1040,245,1120,235,1200,202.7C1280,171,1360,117,1400,90.7L1440,64L1440,320L1400,320C1360,320,1280,320,1200,320C1120,320,1040,320,960,320C880,320,800,320,720,320C640,320,560,320,480,320C400,320,320,320,240,320C160,320,80,320,40,320L0,320Z"
          ></path>
        </svg> */}
        <div className="hidden lg:block">
          <svg
            className="absolute bottom-0 left-0 lg:h-[40rem]"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 1440 320"
            // height="40rem"
          >
            <path
              fill=" #fff"
              fillOpacity="1"
              d="M0,128L40,128C80,128,160,128,240,122.7C320,117,400,107,480,122.7C560,139,640,181,720,213.3C800,245,880,267,960,277.3C1040,288,1120,288,1200,240C1280,192,1360,96,1400,48L1440,0L1440,320L1400,320C1360,320,1280,320,1200,320C1120,320,1040,320,960,320C880,320,800,320,720,320C640,320,560,320,480,320C400,320,320,320,240,320C160,320,80,320,40,320L0,320Z"
            ></path>
          </svg>
        </div>
      </div>
    </>
  );
}
