import Head from "next/head";
import React from "react";
import { BsArrowRight } from "react-icons/bs";

const Workspace = () => {
  return (
    <>
      <Head>
        <title>Travel Manager | Workspace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full h-fit lg:h-screen overflow-y-auto">
        <div className="lg:mx-8 lg:my-6 mx-3 my-2 flex flex-col gap-8">
          <div className="flex flex-col gap-1 lg:gap-2">
            <p className="text-xl lg:text-2xl font-semibold">Your Workspace</p>
            <p className="text-base lg:text-lg text-[#b8bbbf]">Welcome, xxx</p>
          </div>

          {/* overview & cards */}
          <div className="flex flex-col gap-4">
            <p className="font-semibold text-xs lg:text-sm">Overview</p>
            <div className="flex flex-wrap gap-6 lg:gap-20">
              {/* card 1 */}
              <div className="border border-t-[6px] border-t-[#ddaa3d] bg-white shadow-lg w-96 h-40 flex flex-col justify-evenly">
                <p className="tracking-wide bg-[#fbf6eb] text-xs lg:text-sm font-semibold py-2 pl-4">
                  Today&#39;s Agenda
                </p>
                <p className="tracking-wide text-xs text-center my-auto">
                  You don&#39;t have any event scheduled for today.{" "}
                  <span className="text-[#ddaa3d]">Add</span>
                </p>
              </div>
              {/* card 2 */}
              <div className="border border-t-[6px] border-t-[#ddaa3d] bg-white shadow-lg w-96 h-48 flex flex-col">
                <div className="tracking-wide flex items-center justify-between bg-[#fbf6eb] py-2 px-4">
                  <p className="text-xs lg:text-sm font-semibold">
                    Activity Report
                  </p>
                  <p className="text-[#ddaa3d] text-[10px] flex items-center gap-1">
                    view full activity report
                    <BsArrowRight />
                  </p>
                </div>
                <div className="flex gap-1 justify-between mx-2 items-center text-xs text-[#b8bbbf] mt-3">
                  <div className="w-52 h-[2px] border"></div>
                  <p>Tuesday (18th sept. 2019)</p>
                </div>
                <div className="flex flex-col mx-2 tracking-wide">
                  <p className="text-sm text-[#b8bbbf]">
                    You added a new client
                  </p>
                  <p className="text-[11px]  text-[#ddaa3d]">Odusote Mayokun</p>
                  <div className="text-[10px] text-[#3e3d3b] border-l-2 border-[#ddaa3d] bg-[#fbf6eb] w-fit px-2">
                    Status: pending
                  </div>
                </div>
              </div>
              {/* card 3 */}
              <div className="border border-t-[6px] border-t-[#ddaa3d] bg-white shadow-lg w-96 h-48 flex flex-col">
                <div className="tracking-wide flex items-center justify-between bg-[#fbf6eb] py-2 px-4">
                  <p className="text-xs lg:text-sm font-semibold">
                    Task that are due
                  </p>
                  <p className="text-[#ddaa3d] text-[10px] flex items-center gap-1">
                    Create Task
                    <BsArrowRight />
                  </p>
                </div>
                <div className="bg-[#fbf6eb] flex flex-col gap-1 mt-3 text-xs mx-4">
                  <p className="px-2 mt-2 font-semibold">
                    Follow up with{" "}
                    <span className="text-[#ddaa3d]">Odusote</span>
                  </p>
                  <div className="flex gap-4 px-2 mb-2">
                    <p>Due on: 1/21/2021</p>
                    <p>Created on: 1/15/2021</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Workspace;
